spring.application.name=backend

# Supabase Connection Settings
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.kbxsygbthdibmryugums
spring.datasource.password=Irusha@Dilshan
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true